// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBulkCustomRule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddCustomRule(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddCustomRuleWithName(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DeleteCustomRule(arg1:string):Promise<void>;

export function EmitShowNotification(arg1:string):Promise<void>;

export function GetDefaultRules():Promise<Array<main.RedactionRule>>;

export function GhostHideToTray():Promise<void>;

export function LoadRules():Promise<Array<main.RedactionRule>>;

export function RedactText(arg1:string,arg2:boolean):Promise<main.RedactResult>;

export function ResetRules():Promise<Array<main.RedactionRule>>;

export function RestoreGhostModeFromSettings(arg1:boolean):Promise<void>;

export function SaveRules(arg1:Array<main.RedactionRule>):Promise<void>;

export function SetGhostModeEnabled(arg1:boolean):Promise<void>;

export function SimulatePasteAfterDelay(arg1:number):Promise<void>;

export function StartClipboardTimer(arg1:string):Promise<void>;

export function StartGhostWatcher():Promise<void>;

export function ToggleSatelliteMode(arg1:boolean):Promise<void>;

export function UpdateClipboard(arg1:string):Promise<void>;
