// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBulkCustomRule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddBulkCustomRule'](arg1, arg2, arg3, arg4);
}

export function AddCustomRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCustomRule'](arg1, arg2, arg3, arg4, arg5);
}

export function AddCustomRuleWithName(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddCustomRuleWithName'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteCustomRule(arg1) {
  return window['go']['main']['App']['DeleteCustomRule'](arg1);
}

export function EmitShowNotification(arg1) {
  return window['go']['main']['App']['EmitShowNotification'](arg1);
}

export function GetDefaultRules() {
  return window['go']['main']['App']['GetDefaultRules']();
}

export function GhostHideToTray() {
  return window['go']['main']['App']['GhostHideToTray']();
}

export function LoadRules() {
  return window['go']['main']['App']['LoadRules']();
}

export function RedactText(arg1, arg2) {
  return window['go']['main']['App']['RedactText'](arg1, arg2);
}

export function ResetRules() {
  return window['go']['main']['App']['ResetRules']();
}

export function RestoreGhostModeFromSettings(arg1) {
  return window['go']['main']['App']['RestoreGhostModeFromSettings'](arg1);
}

export function SaveRules(arg1) {
  return window['go']['main']['App']['SaveRules'](arg1);
}

export function SetGhostModeEnabled(arg1) {
  return window['go']['main']['App']['SetGhostModeEnabled'](arg1);
}

export function SimulatePasteAfterDelay(arg1) {
  return window['go']['main']['App']['SimulatePasteAfterDelay'](arg1);
}

export function StartClipboardTimer(arg1) {
  return window['go']['main']['App']['StartClipboardTimer'](arg1);
}

export function StartGhostWatcher() {
  return window['go']['main']['App']['StartGhostWatcher']();
}

export function ToggleSatelliteMode(arg1) {
  return window['go']['main']['App']['ToggleSatelliteMode'](arg1);
}

export function UpdateClipboard(arg1) {
  return window['go']['main']['App']['UpdateClipboard'](arg1);
}
